ADD PR template
LearnWeb3DAO/Freshman-Track pull request #35
Opened 2023-03-01 04:53 UTC by yashdev9274

I have added PR template that looks like this

![image](https://user-images.githubusercontent.com/72986960/222048035-aec4eba8-51cd-42a7-891c-829dea7b9c8d.png)

2023-03-01 08:37 UTC, yanukadeneth99 commented
Hey @yashdev9274, thanks for the addition! I think this is great. I'll go through this properly and get back to you 😄

2023-03-01 18:29 UTC, yanukadeneth99 requested changes
I think this looks great, however, @haardikk21 what do you think of something like this since y'all are gonna move away from GitHub eventually?

2023-03-01 18:29 UTC, yanukadeneth99 commented on .github/PULL_REQUEST.md
> +## Fixes Issue
We can remove this section since we don't rely much in GitHub Issues.

2023-03-01 18:29 UTC, yanukadeneth99 commented on .github/PULL_REQUEST.md
> +[x] - Correct; marked as done
Maybe we can add few examples here.

2023-03-01 18:38 UTC, yashdev9274 commented
> I think this looks great, however, @haardikk21 what do you think of something like this since y'all are gonna move away from GitHub eventually?

Move away from GitHub??? What does that mean???

2023-03-04 17:33 UTC, yashdev9274 commented
Hey @yanukadeneth99 any update on this PR?

2023-03-04 18:13 UTC, yanukadeneth99 commented
Hey @yashdev9274, I'm waiting for a word from @haardikk21. He's extremely busy with the new V2 coming out. 😉

2023-03-06 15:39 UTC, haardikk21 commented
This is a good change for the meantime, but yes starting with v2 we will be shifting off Github.

2023-03-06 15:41 UTC, yanukadeneth99 requested changes
Could you do the changes suggested?

2023-03-08 17:11 UTC, yashdev9274 commented
> Could you do the changes suggested? @yashdev9274

yes I'll make the required changes

2023-03-16 19:53 UTC, yanukadeneth99 commented
Any updates @yashdev9274?

2023-03-18 08:46 UTC, yanukadeneth99 commented
Closing this for inactivity. Tag me to re-open this back.

2023-03-18 08:46 UTC, closed without merging