Specified where to add script tag
LearnWeb3DAO/Freshman-Track pull request #7
Opened 2022-09-28 09:40 UTC by rahulsingh3526

Earlier we have specified above that you can add styles in your head folder . So it might create confusion and they may add it in the head even though it might work but in the video done by snoopies she added it inside the body tag.

2022-09-29 14:11 UTC, haardikk21 requested changes

2022-09-29 14:11 UTC, haardikk21 commented on Build-your-first-dApp.md
> +1. Import the Ethers.js source into your `index.html` page inside the `<body>` tag with a new set of script tags:
this should really be inside `<head>` tags not inside `<body>`

2022-10-11 07:33 UTC, rahulsingh3526 commented
Ok will remember it. thanks.

On Thu, Sep 29, 2022 at 7:41 PM Haardik ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Build-your-first-dApp.md
> <https://github.com/LearnWeb3DAO/Freshman-Track/pull/7#discussion_r983601705>
> :
>
> > @@ -193,7 +193,7 @@ Make a new temporary file to hold:
>
>  Back in your local text editor in `index.html`, add the following code to your html page:
>
> -1. Import the Ethers.js source into your `index.html` page inside a new set of script tags:
> +1. Import the Ethers.js source into your `index.html` page inside the `<body>` tag with a new set of script tags:
>
> this should really be inside <head> tags not inside <body>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LearnWeb3DAO/Freshman-Track/pull/7#pullrequestreview-1125384314>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWFCIS4XSMXTLTZ6RIKLZRDWAWPRXANCNFSM6AAAAAAQXS3IW4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-24 15:59 UTC, yanukadeneth99 commented
Hey @rahulsingh3526, closing this.

2022-11-24 15:59 UTC, closed without merging